version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: isekai
      POSTGRES_PASSWORD: isekai_dev_pass
      POSTGRES_DB: isekaigame
      POSTGRES_INITDB_ARGS: "--auth-local=md5"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
